name: GitHub - Activity - README

on:
  push:
   branches:
    - master
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: Jadhielv/github-activity-readme@master
        env:
          GITHUB_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
        with:
          COMMIT_MSG: 'chore: update recent activity'